### ISSUE TITLE
회원가입한 유저가 대표아바타를 추가하지 못한다.

### ISSUE THREAD

**Issue by sinqua** [sinqua/moopi#82]
'아바타 추가' 버튼이 아무런 작동을 하지 않는다.

**Comment by sunyongj1004** [comment]
solved

**Comment by sunyongj1004** [comment]
python 업로드 에러

**Comment by sinqua** [comment]
대표아바타 뿐만 아니라 일반 '게시하기' 버튼에서도 같은 문제 발생. 아바타는 model 스토리지에 정상적으로 저장되지만, optimize 스토리지에 저장되지 못한다.

**Comment by sinqua** [comment]
Blender 씬에 2개 이상의 아바타가 존재하면 VRM Tools 를 이용하여 파일을 출력할 수 없다. 반드시 씬에 1개의 아바타만 존재하도록 백엔드 프로세스를 수정했다.
